import { CefrLevel, VocabItem } from "./types";

const rawRows = [
  ["I did it", "Lo hice"],
  ["Holy shit", "Mierda"],
  ["it was", "Fue ..."],
  ["Awesome", "Asombroso"],
  ["Start from the top!", "Desde el principio"],
  ["I walked into school this morning", "Esta manana entre a la escuela"],
  ["And then", "Y luego"],
  ["I see Colin Corwin", "Yo vi a Colin Corwin"],
  ["Everyone", "Todos"],
  ["Told", "Decir/Contar"],
  ["I see you told everyone", "Veo que tu les dijistes a todos ..."],
  ["How you", ""],
  ["Begged", "Rogo/Suplico/Pidio"],
  ["Begged me", "Suplicarme"],
  ["Suck", "Chupar/Sorber/Mamar"],
  ["I see you told everyone how you begged me to suck face", "Veo que le contastes a todos que me rogaste que te besara"],
  ["Sorry, but I'm not gonna be your boyfriend", "Lo siento, pero no voy a ser tu novio"],
  ["Flatter", "Que no se crea demasiado importante o especial"],
  ["Don't flatter", "No alages"],
  ["yourself", "Tu mismo"],
  ["Don't flatter yourself", "No te alages tu mismo o no te eches flores"],
  ["cancer", "cancer"],
  ["just", "Solo"],
  ["Jerky", "Carne deshidratada"],
  ["Beef", "Sabor carne"],
  ["Beef Jerky", "Carne seca"],
  ["Too", "Tambien"],
  ["Or", "O"],
  ["Fight", "Pelea"],
  ["You cry like a little bitch", "Lloras como una pequena perra"],
  ["Cry", "Lorar"],
  ["Like", "Como/Gustar/Agradar/etc depende del contexto"],
  ["Little", "Pequeno/ chico/diminuto"],
  ["Tasted", "probar/degustar/saber"],
  ["Asked", "Pregunto/Pidio/Solicito"],
  ["If", "Si/Cuando/A ser"],
  ["That's It?", "Eso es todo?"],
  ["Well", "Bien"],
  ["Congratulations", "Felicidades"],
  ["You're suspended", "Te suspendieron"],
  ["Again", "Otra vez"],
  ["Welcome", "Bienvenidos"],
  ["Myself", "Yo mismo"],
  ["Listen", "Escucha"],
  ["Do you really need to go out?", "Tienes que salir?"],
  ["It's your last New Year's with us", "Es tu ultimo ano nuevo con nosotros"],
  ["I know", "Lo se"],
  ["Also", "Tambien"],
  ["It's also my last New Year's with my friends", "Tambien es el ultimo ano con mis amigos"],
  ["Be safe", "Cuidate"],
  ["To say goodbye", "Dile Adios"],
  ["I have gotta go", "Tengo que irme"],
  ["I can't", "No puedo"],
  ["Trust me", "Creeme"],
];

const a1Rows = [
  ["Hello", "Hola", "Greetings"],
  ["Hi", "Hola", "Greetings"],
  ["Good morning", "Buenos dias", "Greetings"],
  ["Good afternoon", "Buenas tardes", "Greetings"],
  ["Good night", "Buenas noches", "Greetings"],
  ["Goodbye", "Adios", "Greetings"],
  ["See you later", "Nos vemos luego", "Greetings"],
  ["Please", "Por favor", "Polite phrases"],
  ["Thank you", "Gracias", "Polite phrases"],
  ["You're welcome", "De nada", "Polite phrases"],
  ["Excuse me", "Disculpa", "Polite phrases"],
  ["I'm sorry", "Lo siento", "Polite phrases"],
  ["Yes", "Si", "Basic answers"],
  ["No", "No", "Basic answers"],
  ["Maybe", "Tal vez", "Basic answers"],
  ["I don't know", "No se", "Basic answers"],
  ["I understand", "Entiendo", "Basic answers"],
  ["I don't understand", "No entiendo", "Basic answers"],
  ["Can you repeat?", "Puedes repetir?", "Classroom"],
  ["How do you say this?", "Como se dice esto?", "Classroom"],
  ["What does it mean?", "Que significa?", "Classroom"],
  ["Open your book", "Abre tu libro", "Classroom"],
  ["Close your book", "Cierra tu libro", "Classroom"],
  ["Listen and repeat", "Escucha y repite", "Classroom"],
  ["Write your name", "Escribe tu nombre", "Classroom"],
  ["My name is Marco", "Me llamo Marco", "Personal info"],
  ["I am a student", "Soy estudiante", "Personal info"],
  ["I am from Mexico", "Soy de Mexico", "Personal info"],
  ["I live in Tijuana", "Vivo en Tijuana", "Personal info"],
  ["I speak Spanish", "Hablo espanol", "Personal info"],
  ["I am learning English", "Estoy aprendiendo ingles", "Personal info"],
  ["How are you?", "Como estas?", "Simple questions"],
  ["I'm fine", "Estoy bien", "Simple answers"],
  ["What's your name?", "Como te llamas?", "Simple questions"],
  ["Where are you from?", "De donde eres?", "Simple questions"],
  ["Where do you live?", "Donde vives?", "Simple questions"],
  ["How old are you?", "Cuantos anos tienes?", "Simple questions"],
  ["I am twenty years old", "Tengo veinte anos", "Personal info"],
  ["This is my friend", "Este es mi amigo", "People"],
  ["My mother", "Mi mama", "Family"],
  ["My father", "Mi papa", "Family"],
  ["My sister", "Mi hermana", "Family"],
  ["My brother", "Mi hermano", "Family"],
  ["My family", "Mi familia", "Family"],
  ["A man", "Un hombre", "People"],
  ["A woman", "Una mujer", "People"],
  ["A boy", "Un nino", "People"],
  ["A girl", "Una nina", "People"],
  ["A teacher", "Un maestro", "People"],
  ["A student", "Un estudiante", "People"],
  ["At home", "En casa", "Home"],
  ["In the kitchen", "En la cocina", "Home"],
  ["In the bedroom", "En el dormitorio", "Home"],
  ["In the bathroom", "En el bano", "Home"],
  ["A table", "Una mesa", "Home"],
  ["A chair", "Una silla", "Home"],
  ["A door", "Una puerta", "Home"],
  ["A window", "Una ventana", "Home"],
  ["My phone", "Mi telefono", "Objects"],
  ["My bag", "Mi mochila", "Objects"],
  ["My keys", "Mis llaves", "Objects"],
  ["A book", "Un libro", "Objects"],
  ["A pen", "Una pluma", "Objects"],
  ["A car", "Un carro", "Transport"],
  ["A bus", "Un autobus", "Transport"],
  ["A taxi", "Un taxi", "Transport"],
  ["On foot", "A pie", "Transport"],
  ["I eat breakfast", "Desayuno", "Daily routine"],
  ["I drink water", "Tomo agua", "Food and drinks"],
  ["I like coffee", "Me gusta el cafe", "Food and drinks"],
  ["I like tea", "Me gusta el te", "Food and drinks"],
  ["I want water", "Quiero agua", "Food and drinks"],
  ["I need food", "Necesito comida", "Food and drinks"],
  ["Bread", "Pan", "Food and drinks"],
  ["Milk", "Leche", "Food and drinks"],
  ["Eggs", "Huevos", "Food and drinks"],
  ["Rice", "Arroz", "Food and drinks"],
  ["Chicken", "Pollo", "Food and drinks"],
  ["An apple", "Una manzana", "Food and drinks"],
  ["A banana", "Un platano", "Food and drinks"],
  ["I wake up", "Me despierto", "Daily routine"],
  ["I go to work", "Voy al trabajo", "Daily routine"],
  ["I go to school", "Voy a la escuela", "Daily routine"],
  ["I study English", "Estudio ingles", "Daily routine"],
  ["I watch TV", "Veo television", "Daily routine"],
  ["I sleep at night", "Duermo en la noche", "Daily routine"],
  ["Today", "Hoy", "Time"],
  ["Tomorrow", "Manana", "Time"],
  ["Yesterday", "Ayer", "Time"],
  ["Now", "Ahora", "Time"],
  ["Later", "Mas tarde", "Time"],
  ["In the morning", "En la manana", "Time"],
  ["In the afternoon", "En la tarde", "Time"],
  ["At night", "En la noche", "Time"],
  ["One", "Uno", "Numbers"],
  ["Two", "Dos", "Numbers"],
  ["Three", "Tres", "Numbers"],
  ["Four", "Cuatro", "Numbers"],
  ["Five", "Cinco", "Numbers"],
  ["Ten", "Diez", "Numbers"],
  ["Twenty", "Veinte", "Numbers"],
  ["Monday", "Lunes", "Days"],
  ["Tuesday", "Martes", "Days"],
  ["Wednesday", "Miercoles", "Days"],
  ["Thursday", "Jueves", "Days"],
  ["Friday", "Viernes", "Days"],
  ["Saturday", "Sabado", "Days"],
  ["Sunday", "Domingo", "Days"],
  ["Where is the bathroom?", "Donde esta el bano?", "Useful questions"],
  ["How much is it?", "Cuanto cuesta?", "Useful questions"],
  ["I need help", "Necesito ayuda", "Useful phrases"],
  ["I am hungry", "Tengo hambre", "Feelings"],
  ["I am thirsty", "Tengo sed", "Feelings"],
  ["I am tired", "Estoy cansado", "Feelings"],
  ["I am happy", "Estoy feliz", "Feelings"],
  ["It is cold", "Hace frio", "Weather"],
  ["It is hot", "Hace calor", "Weather"],
  ["It is raining", "Esta lloviendo", "Weather"],
  ["The sun is out", "Hay sol", "Weather"],
];

export const cefrRubric: Record<CefrLevel, string> = {
  A1: "Basic phrases, classroom words, simple connectors and direct everyday meaning.",
  A2: "Short sentences, common social phrases, simple past or immediate situations.",
  B1: "Longer everyday phrases, opinions, intentions and context-dependent meanings.",
  B2: "Natural conversation, idioms, slang, nuance and flexible sentence control.",
  C1: "Advanced precision, register control, abstract topics and subtle style.",
  C2: "Near-native range, accuracy, idiomatic use and effortless expression.",
};

const inferLevel = (english: string): CefrLevel => {
  const wordCount = english.split(/\s+/).filter(Boolean).length;
  const lower = english.toLowerCase();

  if (wordCount <= 1 && !["flatter", "yourself", "tasted", "begged"].includes(lower)) return "A1";
  if (wordCount <= 3 && !lower.includes("flatter")) return "A2";
  if (lower.includes("gotta") || lower.includes("suck face") || lower.includes("don't flatter")) return "B2";
  if (wordCount >= 7) return "B1";
  return "A2";
};

const inferGroup = (english: string): string => {
  const lower = english.toLowerCase();
  if (["and then", "too", "or", "if", "well", "also", "again", "just"].includes(lower)) return "Connectors";
  if (lower.includes("new year") || lower.includes("safe") || lower.includes("goodbye")) return "Social life";
  if (lower.includes("school") || lower.includes("suspended")) return "School";
  if (lower.includes("boyfriend") || lower.includes("flatter") || lower.includes("trust")) return "Relationships";
  if (lower.includes("cry") || lower.includes("fight") || lower.includes("holy")) return "Emotions";
  if (english.split(/\s+/).length > 3) return "Useful sentences";
  return "Vocabulary";
};

export const seedVocabulary: VocabItem[] = rawRows.map(([english, spanish], index) => ({
  id: `seed-${index + 1}`,
  english,
  spanish,
  confidence: index < 8 ? ("normal" as const) : ("bad" as const),
  level: inferLevel(english),
  group: inferGroup(english),
  createdAt: new Date(2026, 5, 28, 20, index).toISOString(),
})).concat(
  a1Rows.map(([english, spanish, group], index) => ({
    id: `a1-seed-${index + 1}`,
    english,
    spanish,
    confidence: "bad" as const,
    level: "A1" as const,
    group,
    createdAt: new Date(2026, 5, 29, 20, index).toISOString(),
  }))
);
